name: Vale Linter
description: The official GitHub Action for Vale -- install, manage, and run Vale with ease.
author: jdkato
branding:
  icon: check
  color: green

inputs:
  styles:
    description: A list of styles to install prior to running Vale.
    required: false

  config:
    description: An externally-hosted configuration file to use.
    required: false

  exclude:
    description: "New line separated string with micromatch patterns to exclude files"
    required: false

  onlyAnnotateModifiedLines:
    description: Only post annotations on lines that have changed within a PR.
    required: false
    default: "false"

  passCondition:
    description: |
      Pass condition that is required for action not to fail.
      Syntax: errors < [MAX_ERRORS]; warnings < [MAX_WARNINGS]; suggestions < [MAX_SUGGESTIONS];
      Example: errors < 1; warnings < 5; suggestions < 10;
      Order of checks and separators does not matter.
      Pass condition will be satisfied only when ALL checks are satisfied.
    required: false

  debug:
    description: "Log debugging information to stdout"
    required: false
    default: "false"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.styles }}
    - ${{ inputs.config }}
    - ${{ inputs.onlyAnnotateModifiedLines }}
    - ${{ inputs.debug }}
