name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Vale
        uses: ./ # Uses an action in the root directory
        with:
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          #config: https://gist.githubusercontent.com/jdkato/171186055d382c6065273fe5a7eeeb61/raw/c6832996f5c77002142df70a3aa2be521fe747a7/.vale.ini
          files: __onlyModified
          exclude: |
            .github/**/*
            README.md
          debug: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     - name: Vale
  #       uses: errata-ai/vale-action@v1.3.0
  #       with:
  #         styles: |
  #           https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
  #           https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
